### ISSUE TITLE
Bottleneck Analyses

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#10]
The end goal is to make sure that our benchmarks scale up as expected (in terms of number of nodes) and we don't bottleneck the scaling with network, disk IO, memory limits. These tasks should not be random I/O-heavy tasks.

The steps are as followed

- Build a model for how lustre I/O scales to a new reference cluster design (Issue #9 ). For the new system, we need to make sure that we have the right ethernet port (10GbE vs 40 GbE) on the storage nodes (the switch itself is 40GbE and it might be that each storage node is capable of sustaining >10Gbs)
- Pick 1 to 2 steps that are the most computationally intensive for the calim pipeline and selected science pipelines and do the following:
    - Measure mean & std runtime vs proc per node to find parallelization per node when computation is not IO or RAM or core limited most of the time (or just take the nominal value of 10 as a starting point)
    - Estimate the number of core used (say the top 5% in terms of timesteps - depends on the pattern)
    - Get, and scale up the RAM use and I/O usage based on data size difference.

Higher Priority
- We should make sure that each compute node has enough RAM for the planned parallelization per node.
- We should make sure that the new lustre I/O can satisfy our projected scaling of data size and compute cluster size (paying attention to the I/O per node, by comparing the RAID6 bandwidth (technically, throughput), the RAID card bandwidth, and the ethernet bandwidth.

Lower Priority
- Figure out if we can trade a compute CPU with fewer cores for other things.

**Comment by caseyjlaw** [comment]
We're well into the implementation now, so I'll close this.
