### ISSUE TITLE
redefine snap monitor points to better leverage Influx/Grafana

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#106]
Looking at the SNAP monitor points, I see a similar construct like so:

`"output_assignment58": 0, "output_assignment59": 0, "output_assignment60": 0, "output_assignment61": 0, "output_assignment62": 0, "output_assignment63": 0}, "input": {"switch_position00": "adc", "power00": 0.0, "rms00": 0.0, "mean00": 0.0, "switch_position01": "adc", "power01": 0.0, "rms01": 0.0, "mean01": 0.0, "switch_position02": "adc", "power02": 0.0, "rms02": 0.0, "mean02": 0.0, "switch_position03": "adc", "power03": 0.0, "rms03": 0.0, "mean03": 0.0, "switch_position04": "adc", "power04": 1.0, "rms04"`

I believe keys with names like: switch_position04, represent the switch_position for chan 04. Likewise for the other key names. The change necessary for Influx/Grafana would be:   "chan": 4, "switch_position": "adc", "power": 0.0, "rms": 0.0, "mean": 0.0, etc. for all metrics related to chan 4.

The reason for this change is because Grafana can be told to create plots and group by 'chan'. The graph will consist of 64 plots with each one labeled by their chan number.  A user can then select interact with the graph and select individual ones of interest.

Nesting also needs to be discussed. Influx does not have any  nesting structures that I'm aware of. I'll take a stab at coming up with a template for the snap/1 monitor data which would maximize grouping in Grafana.

This also applies to the data recorder monitor points.

**Comment by caseyjlaw** [comment]
In support of this, I'll post a link to a feature request made at https://github.com/lwa-project/ovro_data_recorder/issues/14.

By restructuring the f-engine (and maybe data-recorder) monitor points, we can visualize (and automatically identify) bad inputs by ant-pol and save the time and state of all inputs. The saved information could be parsed into a flag table in CASA MS. The real-time flagger (in development) could read from etcd to get an instantaneous set of bad inputs to be flagged.

We can also set up a service to aggregate monitor points into a new etcd key that gets ingested to influx. E.g., `/mon/health` may hold a dict with keys "LWA-nnna" and boolean value, where nnna is ant-pol. The time history of each key should be available with an influx query (i.e., a python client or in grafana).
