### ISSUE TITLE
system configuration spreadsheet update for three new antennas

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#113]
Formalizing Morgan's slack message...
This sheet was updated and should be pushed to etcd:
https://caltech.sharepoint.com/sites/ovro/projects/_layouts/15/guestaccess.aspx?guestaccesstoken=ZAD8nu9Wn3GvkLUIr9ikJP%2BRZ%2FVceXbwKeBH800t2q8%3D&docid=2_00e95ce93f4244686a0604cacbd0e4a2d&rev=1&e=kJ8v7z

**Comment by rh-codebase** [comment]
working on it.

**Comment by rh-codebase** [comment]
81e260a [N]- (HEAD -> main, origin/main) Commit system config file. (2022-04-29T00:25:29+00:00)
The full hash starting with 81e260a will be in the Etcd packet as a check.
