### ISSUE TITLE
1s discrepancy between LWA-SV and OVRO LWA

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#116]
The moon bounce showed there's an exactly 1 second time discrepancy between signals received by the LWA-SV station and the LWA at OVRO; the OVRO LWA is reporting the signal 1s later than it should be.

**Comment by iveydavis** [comment]
sorry for completely missing the questions at the end of this. How I understand it is that they took the unix timestamp from the hdf5 files and compared it to the estimated arrival time for the chirp-- SV was on time and OVRO was off by that 1s. I don't think there was any integration of the data from the hdf5 files.

**Comment by jaycedowell** [comment]
I'm going to try to look at this today in the moon bounce data using WWV.

**Comment by jaycedowell** [comment]
I'm looking at data from 10/20, specifically the 059872_173000000000c6e0d48 file from yesterday's moon bounce experiment.  I'm also using [this page on the contents of WWV and WWVH](https://www.nist.gov/time-distribution/radio-station-wwv/wwv-and-wwvh-digital-time-code-and-broadcast-format) as a reference.  The easiest thing to do is look for what that page calls the "standard time intervals" which are ticks on the second.

To process the data I take the raw file and convert it to spectra using `hdfWaterfall.py` with 16,384 channels and ~2 ms time resolution.  I think down select those data to 50 kHz centered on the 10 MHz WWV single.  After that I then sum XX and YY to make psuedo-Stokes I and then only keep the two channels closest to +/-1 kHz of the carrier.  When you do that you get something like this:

![wwv_221020_1](https://user-images.githubusercontent.com/6718179/197266847-66c1e2d5-1848-4066-80de-9217ab2ced7b.png)

The wide peak at 115 is the 800 ms "minute marker" and you can see the 1 s ticks after that.  Zooming into the minute marker it really does look like it is 800 ms wide:

![wwv_221020_2](https://user-images.githubusercontent.com/6718179/197267147-b6c9f5f0-5e29-4f15-8e40-7bd915982a3c.png)

If I pull out the timestamp for that first "x" in the initial rise of the marker I get that it is at 17:32:00.004.  Based on that I would say that there is no 1 s offset.  I'll try to LWA-SV data next.

**Comment by jaycedowell** [comment]
For the LWA-SV file 059872_004750344 I follow the same process and see:

![wwv_221020_SV_1](https://user-images.githubusercontent.com/6718179/197271945-42068d9b-0d62-4b49-a072-58cb2b746c7a.png)

That's the same minute marker and it starts at 17:32:00.003.  For at least this one snapshot everything looks ok.

**Comment by iveydavis** [comment]
That's great to hear that it doesn't look like there's a time discrepancy now! I don't know if this is because there _was_ a problem that's now resolved, or if there was an error in Mark's analysis of the original observation. I'd be interested to see his analysis of this data too.

**Comment by jaycedowell** [comment]
Yeah, it's not clear.  It could also be that there is a discrepancy in the time tagging in the power beam data that were used previously.  I did collect power beam data for these observations so that might be something to look at.  Maybe the second ticks can be pulled out of that even though the spectral resolution is much lower.

**Comment by jaycedowell** [comment]
In light of what I'm seeing with #189 it could be both that the time keeping in the F-engines/X-engines/T-engine is ok but the time keeping in the power beam recorders is not.

**Comment by caseyjlaw** [comment]
Resolved with new commit, as described in #189
