### ISSUE TITLE
Order new memory module for GPU09

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#118]
One memory stick needed for GPU09

**Comment by rh-codebase** [comment]
memory arrived.

**Comment by rh-codebase** [comment]
Installed planned around the time the site wide UPS is installed. Unless something crops up which indicates this is needed sooner.

**Comment by rh-codebase** [comment]
ping.

**Comment by Princemongo** [comment]
Installed module when site power was down.
