### ISSUE TITLE
Address CVE announcements from Github

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#12]
Github scans and reports if there are any CVE against the codebase. The latest is a CVE against Pillow.

**Comment by yupinghuang** [comment]
Resolved
https://github.com/ovro-lwa/distributed-pipeline/commit/1821497009d6e4afcd6ee221e817148bef6effaf

I've been keeping an eye on these. The moderate sev ones will be resolved soon.
