### ISSUE TITLE
GPU servers unreachable

### ISSUE THREAD

**Issue by kathrynplant** [ovro-lwa/lwa-issues#124]
The gpu servers aren't responding to pings from lwamaas.

**Comment by rh-codebase** [comment]
thermal shutdown. bringing hosts back up and retuning.

**Comment by caseyjlaw** [comment]
Ooh, a real world test. Do you think it worked as intended?
Looking at the Grafana "LWA Shutdown" dashboard, I see that there is a "stale temp" state change. If that was the trigger, then the shutdown was caused by a lack of measurement, rather than high temp. Is that the right interpretation?

**Comment by rh-codebase** [comment]
new setpoint at 24.5C

**Comment by rh-codebase** [comment]
not sure what you are looking at but the shutdown was indeed due to the setpoint being reached. There is some tuning to do in regards to the shutdown message being sent before the machine shuts down.
