### ISSUE TITLE
CISCO switch not passing 10.41.0.64/26 network traffic

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#129]
The GPU hosts have 2 interfaces within the 10.41.0.0/24 network to allow the SNAPS to transfer packets to each one. These interfaces are:
10.41.0.0/27
10.41.0.64/26
The latter is wider to include the CalIm nodes. The calim nodes are on the same /26 with lwacalimhead at 10.41.0.74/26
lwacalim00 at 10.41.0.75/26  and sequentially upwards.

The lxdlwagpuXX nodes are on 1 cisco switch and the lwacalimXX nodes on another. The switches are connected together with a single fiber.

The lwacalimXX nodes can see each other and respond to ping. Likewise for the lxdlwagpuXX nodes. However, lwacalimXX cannot ping lxdlwagpuXX and vise versa.

The calim and gpu nodes also have a 10.40.0.0/24 interface as well and traffic between all nodes on this network across the same 2 switches works as expected.

**Comment by jack-h** [comment]
Looking at the new calim switch, I found all the GPU nodes in the switch's
mac address-table on incorrect ports (I'm guessing the config was just
copied from the digital rack switch).
I've removed all these static entries and now can ping from GPU01 (
10.41.0.65/26) to lwacalim00 (10.41.0.75/26).
I think probably all paths should now be working.

One thing I did notice is that on the calim switch port 13 is set to 4x10G
breakout. I've no idea whether this is deliberate, but if there are issues
with that port then possibly this is the problem.

**Comment by rh-codebase** [comment]
Hmm. I didn't do any config copy between switches. Is there a reason this type of switch doesn't learn the MAC addresses of hosts connected to the ports? In any case, this looks to be fixed. I don't know why port 13 needs to be 4x10G. All the calim nodes are 40G. This switch did come from campus so maybe 4x10G was needed there.
