### ISSUE TITLE
Can't start up the gpu pipelines on gpu06, 07, 08

### ISSUE THREAD

**Issue by marinanderson** [ovro-lwa/lwa-issues#131]
Ran my usual `sudo /etc/init.d/openibd restart` in case those nodes had been rebooted recently (I know at least gpu08 was down recently...), but didn't work.

**Comment by jaycedowell** [comment]
This could be related to some testing I did on the beamformer before I went on vacation but I thought I left everything in a working state.

**Comment by jaycedowell** [comment]
Yeah, I think so.  Try it now.

**Comment by jaycedowell** [comment]
Everything _seems_ ok this afternoon for my tests.

**Comment by jaycedowell** [comment]
This particular issue is resolved.  It came about from installing lwa352_pipeline_control with a `pip install` instead of a `python setup.py install`.
