### ISSUE TITLE
docker-ce.repo on lwacalimhead

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#132]
`/etc/yum.repos.d/docker-ce.repo` seems to break RHEL package manager's dependency resolution. It seems like this repo only exists on the head node. Is it safe to remove?

**Comment by yupinghuang** [comment]
I can see from history that Rick tried to look for some container related stuff...podman is more or less a drop-in replacement in the RedHat ecosystem, but I've installed docker outside of the package manager on RHEL 8 before and that's the recommended solution if one wants to use docker.

It doesn't seem like anything got installed, though? And the repo file just sits there. Rick, let me know what your use case on the node for docker is and I can figure out how to get there.

**Comment by rh-codebase** [comment]
You can remove anything related to docker or I can if you wish. Sorry for leaving that trash behind.

**Comment by yupinghuang** [comment]
For the record, https://download.docker.com/linux/rhel/docker-ce.repo should work whereas https://download.docker.com/linux/centos/docker-ce.repo does not.

**Comment by rh-codebase** [comment]
nice. It's unclear if docker might interfere with networking on these hosts. It doesn't seem to play nice with the LXD containers. I'm still fighting to get k8s running in a multi-LXD container env. but that's another story.
