### ISSUE TITLE
GPU nodes power supply issues

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#137]

**Comment by rh-codebase** [comment]
traced problem back to a faulty circuit breaker. Handing off to Mark.

**Comment by rh-codebase** [comment]
turns out the breaker is good but the powerstrip contains 2 fuses and one was blown. Did find that 1 powersupply on GPU03 was bad. Some power supply LED's were showing amber and didn't turn green until  the PS was removed and reseated. 2 PS will be ordered.

**Comment by Princemongo** [comment]
A power supply and a spare were ordered. One was installed on 5 Sept.
