### ISSUE TITLE
astm-oss4 -- one OST failed to mount

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#139]

**Comment by marinanderson** [comment]
On oss4, ran the following for ost10:

`e2fsck -f -y -C 0 -E shared=delete /dev/sdc`

Finished within ~18 hours, and was able to remount ost10. Below is the output at the end of the fsck process:

> [QUOTA WARNING] Usage inconsistent for ID 0:actual (14807826292736, 15884616) != expected (8364222423040, 8915484)
[QUOTA WARNING] Usage inconsistent for ID 2335:actual (1012651933696, 155854) != expected (1012647739392, 155853)
[QUOTA WARNING] Usage inconsistent for ID 5692:actual (104663048192, 23186) != expected (66700652544, 14423)
[QUOTA WARNING] Usage inconsistent for ID 2827:actual (12377407623168, 8322096) != expected (10317236244480, 8279324)
[QUOTA WARNING] Usage inconsistent for ID 5695:actual (92607074304, 2099) != expected (84639825920, 2071)
[QUOTA WARNING] Usage inconsistent for ID 5669:actual (335715344384, 158978) != expected (335718490112, 158978)
[QUOTA WARNING] Usage inconsistent for ID 5687:actual (13501734912, 1068) != expected (17252745216, 1097)
[QUOTA WARNING] Usage inconsistent for ID 5674:actual (693638557696, 782455) != expected (640416145408, 782437)
[QUOTA WARNING] Usage inconsistent for ID 5679:actual (659024441344, 962092) != expected (652620726272, 960889)
[QUOTA WARNING] Usage inconsistent for ID 5680:actual (2063199744000, 5148315) != expected (1766082703360, 5086628)
[QUOTA WARNING] Usage inconsistent for ID 5697:actual (1515437330432, 140950) != expected (1515438379008, 140950)
[QUOTA WARNING] Usage inconsistent for ID 5685:actual (269595082752, 89808) != expected (269599145984, 89808)
[QUOTA WARNING] Usage inconsistent for ID 5686:actual (55371890688, 161355) != expected (55372939264, 161355)
[QUOTA WARNING] Missing quota entry ID 2844
[QUOTA WARNING] Missing quota entry ID 5671
Update quota info for quota type 0? yes
>
>[QUOTA WARNING] Usage inconsistent for ID 0:actual (14764611321856, 15881438) != expected (1415241465856, 7456777)
[QUOTA WARNING] Usage inconsistent for ID 100:actual (19272101879808, 15969543) != expected (15922898210816, 15712356)
Update quota info for quota type 1? yes
>
>
>lustre-OST000a: ***** FILE SYSTEM WAS MODIFIED *****
lustre-OST000a: 31973046/34335744 files (0.2% non-contiguous), 8317598810/8789950464 blocks
