### ISSUE TITLE
mcs containers not coming up

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#142]

**Comment by rh-codebase** [comment]
could be related to a SNAP update of LXD on 2022-08-13. Devs announced a new version release so waiting for it to propagate to the distribution nodes in hopes that it fixes this. I've seen this before with SNAP updates breaking LXD and upstream usually fixes the issue fairly quickly.

**Comment by rh-codebase** [comment]
starting work on the lxd containers this afternoon.

**Comment by rh-codebase** [comment]
LXD containers are back up. WebUI functional although there is an issue pulling the Excel spreadsheet from SharePoint. Maybe 2-factor auth has gotten in the way(will submit new issue). The new antenna config has been pushed which should fix issue #146. Grafana seeing ARX data flow through. Closing but will open some new issues.
