### ISSUE TITLE
Antenna position mapping issue

### ISSUE THREAD

**Issue by dgary50** [ovro-lwa/lwa-issues#146]
I find that "from lwa_antpos import mapping" fails when attempting to determine list of online antennas.  The list returns 380 entries with the first (LWA000) returning an online status as NaN and those after LWA-366 all NaN in both their names and online status.  The error states that NaNs are not allowed.  Maybe this is a format error in an xlsx file?

**Comment by caseyjlaw** [comment]
For progress on general mnc, you should watch issue #142.

**Comment by rh-codebase** [comment]
new config pushed into etcd earlier today. Keeping open to track parsing of spreadsheet.

**Comment by caseyjlaw** [comment]
I updated the spreadsheet in the lwa-antpos repo. While testing, I found the bug and changed the way it parses the spreadsheet (someone must have changed the format).
Installed on lwacr and tested there.
