### ISSUE TITLE
trouble importing from lwa_antpos

### ISSUE THREAD

**Issue by kathrynplant** [ovro-lwa/lwa-issues#157]
Using ipython on the cosmic ray server, when I do: from lwa_antpos import mapping 
I get the following error:
Read antpos from xlsx file in repo

-
ValueErrorTraceback (most recent call last)
<ipython-input-1-2bc895e9f724> in <module>
     13 from scipy import optimize as oz
     14 from scipy import stats as st
---> 15 from lwa_antpos import mapping

~/anaconda3/envs/casa/lib/python3.6/site-packages/lwa_antpos/__init__.py in <module>
     18 
     19 if 'online' in lwa_df.columns:
---> 20     antnames = lwa_df[lwa_df.online].index
     21 else:
     22     antnames = lwa_df.index

~/anaconda3/envs/casa/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2894 
   2895         # Do we have a (boolean) 1d indexer?
-> 2896         if com.is_bool_indexer(key):
   2897             return self._getitem_bool_array(key)
   2898 

~/anaconda3/envs/casa/lib/python3.6/site-packages/pandas/core/common.py in is_bool_indexer(key)
    132                 na_msg = "Cannot mask with non-boolean array containing NA / NaN values"
    133                 if isna(key).any():
--> 134                     raise ValueError(na_msg)
    135                 return False
    136             return True

ValueError: Cannot mask with non-boolean array containing NA / NaN values

**Comment by caseyjlaw** [comment]
I had a fix in the development branch. It is now installed on lxdlwacr and lxdlwagpu09.
