### ISSUE TITLE
Missing 40G interface on lwacalim06

### ISSUE THREAD

**Issue by jaycedowell** [ovro-lwa/lwa-issues#159]
It's not there:
```
(base) [pipeline@lwacalim06 ~]$ lspci | grep -i ether
44:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
44:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
```

**Comment by rh-codebase** [comment]
similar to issue #144. Manual removal and inserting the card will likely be needed.

**Comment by rh-codebase** [comment]
logging in and rebooting system brought back interface:

(base) [ubuntu@lwacalim06 ~]$ lspci | grep -i ether
44:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
44:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
c1:00.0 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)
c1:00.1 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)

**Comment by caseyjlaw** [comment]
lwacalim06 is currently down. Maybe this is a broader issue?

**Comment by yupinghuang** [comment]
on it

**Comment by yupinghuang** [comment]
IPMI reports that the host was powered off so I turned it on. Seems like lwacalim06 has been off since the hour after Oct 27 15:10 UTC. Nobody was logged in at the time. These issues appear unrelated.

**Comment by caseyjlaw** [comment]
Thank you for getting that back up.
