### ISSUE TITLE
Verify f-engine noise statistics

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#165]
Set all inputs to the same noise sequence. 
Verify, using autocorr block, that blocks of 16 inputs are identical, and that there is a spike in the DC bin.
Verify all bit stats are identical

**Comment by rlbyrne** [comment]
Done, with `./test_internal_noise.py --samenoise snap03`
Code is available [here](https://github.com/realtimeradio/caltech-lwa/blob/66d771fe4e91c4760df37996d7c4d431a7f135b2/control_sw/tests/test_internal_noise.py)
