### ISSUE TITLE
Verify f-eng noise statistics when set differently

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#166]
Set all inputs to one of 4 random noise generators.
Check inputs associated with the same noise sources are identical, and that inputs associated with different inputs are different.

**Comment by rlbyrne** [comment]
Done, with `./test_internal_noise.py --diffnoise snap03`
Code is available [here](https://github.com/realtimeradio/caltech-lwa/blob/66d771fe4e91c4760df37996d7c4d431a7f135b2/control_sw/tests/test_internal_noise.py)
