### ISSUE TITLE
Verify f-eng coarse delay

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#168]
Apply correlated digital random noise to all inputs.
Apply random coarse delay corrections.
Verify correlation phase slopes match expected.

**Comment by rlbyrne** [comment]
Done, with `./test_internal_noise.py --delay snap03`
Code is available [here](https://github.com/realtimeradio/caltech-lwa/blob/66d771fe4e91c4760df37996d7c4d431a7f135b2/control_sw/tests/test_internal_noise.py)
