### ISSUE TITLE
Test bifrost beamformer with random data/weights

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#177]
Verifying output matches a simple python matrix multiply operation.
This test uses the control library to set weights.

**Comment by iveydavis** [comment]
Manipulating the calibration tables and confirming the output

**Comment by jack-h** [comment]
If you want all inputs to the beamformer to be constant and known, you could use the F-engine "ramp" test mode (https://raw.githubusercontent.com/realtimeradio/caltech-lwa/master/docs/build/latex/LWA352SNAP2F-Engine.pdf)

**Comment by jack-h** [comment]
`write_freq_ramp()`
`tvg_enable()`

![Image](https://user-images.githubusercontent.com/1402492/199567801-0d87ad58-9015-4d54-aef4-bcbee6e86b0a.png)

**Comment by iveydavis** [comment]
Starting the x-engine pipelines won't overwrite the use of f-engine test vectors will it? And Is there a reason to use the test vector block instead of injecting noise or using the dummy source functionality of bifrost?

**Comment by jack-h** [comment]
Correct, starting the X-engine pipelines won't affect what the F-engines
are doing.
The main benefit of using the test vectors on the F-engines is that it's
easy, and you know exactly what is going into the B/X pipelines. Generating
data in bifrost would also work, but tests less of the pipeline. Testing
with noise would be good too, it's just a little tricky to know what 4-bit
data ends up going to the X/B engines after FFT / requantization processing

**Comment by caseyjlaw** [comment]
Ran the beamformer_sum_test.py and beamformer_test.py on gpu09 and am consistently getting "Match OK". Also suitable for this issue.
