### ISSUE TITLE
Verify t-eng signal path

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#187]
Confirm signals are transmitted through system, and that all subsystems are properly connected. 
Data recording system can be started for some defined duration.

**Comment by jaycedowell** [comment]
I'm not sure what to say about this.  Data from the voltage beam make it to the T-engine and these are being processed and written to disk.

**Comment by caseyjlaw** [comment]
Sounds like a "passes test" to me!
