### ISSUE TITLE
Test t-eng spectral properties

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#188]
Confirm that spectrum order is correct at each stage through to final recorded data. 
Spur checks -- Confirm that no unexpected spikes occur in the passbands.

**Comment by jaycedowell** [comment]
#116 works towards this some since it focuses on extracting the WWV second ticks from the 10 MHz signal.  Those data are from the second day of the recent moon bounce experiment (MJD 59872).

**Comment by jaycedowell** [comment]
There was also at least one successful pulsar observation with the T-engine.  We might want to repeat that during a better interference environment.  A fringe test with LWA1/LWA-SV would also be nice.

**Comment by caseyjlaw** [comment]
Marin also saw 1-channel offset between power/voltage beams.

**Comment by jaycedowell** [comment]
https://github.com/lwa-project/ovro_data_recorder/issues/30

**Comment by jaycedowell** [comment]
Gain settings are working.

**Comment by jaycedowell** [comment]
Everything seems ok modulo https://github.com/ovro-lwa/lwa-issues/issues/460.
