### ISSUE TITLE
Reproduce power beam from voltage beam

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#189]
Record voltage beam and verify that power beam can be generated from time beam data product.

**Comment by jaycedowell** [comment]
I'm looking at this using data from the third day of the moon bounce experiment (MJD 59873) where I have simultaneous power and voltage beam data.  For the power beam data I focus on the ~10 +/- 5 MHz region where the voltage beam was tuned to and look at the first 200 s of data.

Processing the voltage beam data into spectra with a similar temporal resolution (~0.8 ms vs ~1 ms) things look ok:
![voltage_power_1](https://user-images.githubusercontent.com/6718179/198382373-e0d41186-00a7-48be-b223-04b2c1f699fa.png)
and there is qualitatively good correspondence between the two.

If I integrate over frequencies and plot power as a function of time I see:
![voltage_power_2](https://user-images.githubusercontent.com/6718179/198382761-f7c6fa48-722a-4fc5-838d-2f29557c815f.png)
There is a time offset here between the voltage beam (blue) and the power beam (orange) of about 160 ms.  If I adjust the power beam by this amount you get the green line and that agrees with the blue one.

To figure out which time is correct I looked at the 10 MHz WWV signal as in #116:
![voltage_power_3](https://user-images.githubusercontent.com/6718179/198383224-cd496d30-2dd5-4774-9ac8-6a0e871b1e58.png)
In this plot "Full Res. Voltage" refers to a processed voltage beam data product with ~2 kHz spectral resolution at the same ~0.8 ms time resolution.  The peak in the "full res." data is close to the expected time of the second tick (the vertical dotted line) and there is a corresponding peak, albeit at lower SNR, for the blue line.  The second tick also shows up in the power beam (orange) at the same significance as in the blue but about 160 ms later.  At this point I'm not really sure where this 160 ms lag in the power beam comes from.

**Comment by jaycedowell** [comment]
I looked at the data from MJD 59872 and I seem something similar in the integrate power as a function of time:
<img width="579" alt="Screen Shot 2022-10-28 at 7 08 41 AM" src="https://user-images.githubusercontent.com/6718179/198599617-b1e557a0-fcfa-4185-a0f7-11074d41bc7a.png">
The offset in this case is about ~-400 ms.  400 ms is probably a larger error than you can create in the X-engine pipelines so I think this is something with the power beam recorders.

**Comment by jaycedowell** [comment]
Here's a view of the data from MJD 59872 where they have been converted to pseudo-Stokes parameters.
![voltage_power_4](https://user-images.githubusercontent.com/6718179/198691785-2ba74bcd-cb09-4fcd-abf5-933163f342ea.png)

**Comment by jaycedowell** [comment]
I've looked at this again over the last couple of days and I still haven't been able to isolate where things are going wrong.  On the data recorder side I have looked at:
 * time inaccuracy with `LWATime` and the conversion of timetags, 
 * problems keeping track of time within the data recorder, and
 * conversion problems translating a `LWATime` to the tuple stored in the HDF5 file.

One thing I did notice in this last round of testing is that the offset seems to change with restarts of the x-engine pipelines.  It also _may_ drift so that the offset increases with increasing time since the last pipeline restart.  I'm not 100% sure on that last point.

So the clues are:
 1) Restarting the power beam stream changes the offset.
 2) Whatever is causing it needs to not impact the timing of the voltage beam.
 3) The offset _may_ increase the longer the power beam stream is running.

Taking those together it could still be either the x-engines or the data recorder.  (2) really limits where in the x-engine the problem could be, though.  It would be limited to the power beam accumulator and packetizers.  It could also be hiding in some part of the data recorder that I haven't considered.

**Comment by jaycedowell** [comment]
@GregBTaylor and I were talking about this.  It seems like what is needed is a series of test to better determine where this comes from.  Something like:
 1. Run the voltage beam and 2/3/4 power beams all pointing at the same (fixed?) target to see if (a) there is an offset between the power beams, (b) if there is an offset between each power beam and the voltage beam, and (c) if (a) and (b) are consistent with each other.
 2. Repeat the test in (1) with multiple recordings _without_ restarting either the data recorders or the x-engines.
 3. Repeat (1) and possibly (2) with restarting _only_ the data recorders between each set of tests.
 4. Repeat (1) and possibly (2) with restarting _only_ the x-engines between each set of tests.

**Comment by caseyjlaw** [comment]
Sounds like a fairly simple test. For bonus points, we should set this up with a SDF. I'll try to learn how to do that today from Ivey.

**Comment by caseyjlaw** [comment]
For book keeping purposes, I'll list the other time anomaly issues:
#283 
#225 
#116

**Comment by jaycedowell** [comment]
It's been a while so I've taken another look at this.  From my tests today for a zenith pointing and comparing against the voltage beam the offsets are:
 * Beam 1: 360 ms
 * Beam 3: -400 ms
 * Beam 4: -400 ms

Interesting that beams 3 and 4 have the same offset.  After restarting dr-beam-4 I see:
 * Beam 1: 360 ms
 * Beam 3: -400 ms
 * Beam 4: 0 ms

That causes a change in beam 4.  I did not expect that.  After resetting the destination address/port for beam 3:
 * Beam 1: 360 ms
 * Beam 3: -400 ms
 * Beam 4: 0 ms

Same as before.  Restarting dr-beam-1 now gives:
 * Beam 1: -490 ms
 * Beam 3: -400 ms
 * Beam 4: 0 ms

So it seems to follow the data recorder but I can't think of what the mechanism would be.  For good measure, another restart of dr-beam-1 gives:
 * Beam 1: -400 ms
 * Beam 3: -400 ms
 * Beam 4: 0 ms

**Comment by jaycedowell** [comment]
https://github.com/lwa-project/ovro_data_recorder/commit/982333f868b1e94c92272042585d21ef90d84172 helps and the offset is now ~1 ms, slightly longer than the native power beam temporal resolution.

**Comment by jaycedowell** [comment]
This ~1 ms error needs a bifrost patch (https://github.com/realtimeradio/bifrost/pull/3).  This gets a little tricky because I don't know where bifrost on calim comes from.  Is it still from my `/home/pipeline/bifrost` directory?  That's at least what I used for testing this patch.

**Comment by caseyjlaw** [comment]
At least the gpu servers get it from the bifrost submodule in the [x-engine code](https://github.com/realtimeradio/caltech-bifrost-dsp/blob/main/deploy). The bifrost module is separately available in `lwa-shell`, which is how Rick does most deployment. @rh-codebase do you know how bifrost is installed on cal-im?

**Comment by jaycedowell** [comment]
The version of bifrost in `lwa-shell` wouldn't be the right one since it points to the original ledatelescope version.  What's in the bifrost sub-module from caltech-bifrost-dsp is closer but it needs a little tweaking for calim (no xgpu or CUDA support; that unmerged patch I mentioned earlier).

**Comment by caseyjlaw** [comment]
Would you suggest we change the remote for the bifrost in `lwa-shell` and then you can do a PR to add a deployment script?

**Comment by jaycedowell** [comment]
I'm not sure.  Are any of the other packages using bifrost or it is only ovro_data_recorders and caltech-bifrost-dsp?  If it's only those two it might make sense drop bifrost from `lwa-shell` and add a submodule for bifrost into ovro_data_recorders.

**Comment by caseyjlaw** [comment]
This would only be for ovro_data_recorders, so a submodule would make sense. You could fix it to a particular commit/version too.

**Comment by jaycedowell** [comment]
`main` currently as a bifrost submodule in it and a new `deploy` script that will install this version of bifrost.  It seems to work on the T-engine but I haven't tried it on calim.  One thing to note about it is that it currently doesn't try to build CUDA support on calim.  Maybe you want to change that based on @nkosogor's beamformer work?

**Comment by caseyjlaw** [comment]
We removed the `--disable-cuda` and got `deploy` to work with CUDA support. Could you make that change to the script and we can restart the recorders to close this out?

**Comment by jaycedowell** [comment]
It's in - https://github.com/lwa-project/ovro_data_recorder/commit/5e9dd0532d7cbf4c37a880c19b93003e7b0bfce4.

When did you want to do the restart?

**Comment by caseyjlaw** [comment]
I think now (late afternoon) is a good time. Are you free now?

**Comment by jaycedowell** [comment]
Sure.  I've started `deploy` on calim01.

**Comment by jaycedowell** [comment]
Everything seems ok.  For the record the bifrost submodule currently points to https://github.com/realtimeradio/bifrost/commit/b739e3d2558cf1783952230c24ff796b7e93438e which is on the https://github.com/realtimeradio/bifrost/tree/lwa352-myrepos branch.
