### ISSUE TITLE
slow visibility data loss

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#205]
`'WARNING: drvs not fully operational: 1 sub-bands error: drvs8002=Packet loss during receive >10% (50.0% missing)'` after I started the data recorder.

**Comment by jaycedowell** [comment]
Did this warning clear on its own?

**Comment by jaycedowell** [comment]
X-engine problems, like a pipeline not running or not configured to output packets, would give you losses in increments of 50%.  Values outside of 50% are harder to pin down because they could be coming from anywhere along the x-engine -> network -> recorder chain.
