### ISSUE TITLE
Are the EQ coeffs in mnc_python config files still used?

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#221]
https://github.com/ovro-lwa/mnc_python/blob/main/config/lwa_config_calim_standard.yaml#L17

**Comment by caseyjlaw** [comment]
It was being used, but not in a transparent and maintainable way. We are migrating these settings to etcd management under /cfg soon.
For now, I'll remove it from here to avoid confusion and eq settings will be done by the subsystem scripts created by Larry.
