### ISSUE TITLE
Beamforming without duration definition

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#222]
It'd be nice to do beamforming via mnc control without having to define the duration of the observation. Right now, stopping the observation prematurely (at least by stopping the data recording service) prevents the hdf5 file from being written properly.

**Comment by jaycedowell** [comment]
The power beam recorders have a 'cancel' command which can be used to stop a recording.  This isn't currently exposed through `mnc.control`.

**Comment by caseyjlaw** [comment]
I could implement this. Two issues come up:
- We could default beamforming to record "endlessly" (e.g., 24 hrs as default), then the data will be written as one large file. As I recall, that makes disk management tricky. Ivey, would you be ok with one large file or do you want a change here?
- Jayce, I see that the cancel command uses a "queue number" to refer to an ongoing recording. Is that number available somewhere? Can one assume it starts at 0 and increments only when there are multiple submitted to the queue?

**Comment by jaycedowell** [comment]
Yes, the queue number starts at zero and increments when there are multiple recordings scheduled.  In the case of multiple records zero will always be the first in time.  I thought I had a way to look up what the queue entries are but I cannot find it in the list of monitoring points.

Alternatively, the cancel command supports canceling by filename (technically the basename of the file).  The active recording file can be queries through the "op-tag" monitoring point.

**Comment by caseyjlaw** [comment]
Would this syntax be correct to cancel (and close file writing) of the power beam 1?
`accepted, response = client.send_command('dr1', 'cancel', mjd='now', mpm='now', queue=0)`

**Comment by jaycedowell** [comment]
`accepted, response = client.send_command('dr1', 'cancel', queue_number=0)`

**Comment by caseyjlaw** [comment]
Added the 'cancel' syntax to the `Control.stop_dr` method. Confirmed with a test.
