### ISSUE TITLE
Display observing problems on web page for observers

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#232]
A dashboard could highlight observing problems relevant to observing and analysis (e.g., antenna flags).

**Comment by caseyjlaw** [comment]
Related: low-freq-sky displays what sources are up and informs analysis. @yupinghuang

**Comment by caseyjlaw** [comment]
Go/no-go and real-time narrow-band image are working.

We need a display of:
- delay solutions
- bad antennas

**Comment by caseyjlaw** [comment]
Parsing caltable (bcal) files to get list of flagged antennas. added table pane showing these flags.
Found syntax to display delays per ant-pol.

**Comment by yupinghuang** [comment]
https://github.com/ovro-lwa/lwa-issues/issues/245

this should probably run as a service, but here's where it's at.

**Comment by caseyjlaw** [comment]
We have many new services to expose problems. Big ones are logger, system health dashboard, and obs state web app.
