### ISSUE TITLE
Power level monitoring in grafana

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#234]
Saturation issues, FFT overflow, requant saturation info should be ingested to influx/grafana.
This will provide understanding of data quality for current observer or for past observations.

**Comment by caseyjlaw** [comment]
F-eng data going into influx and grafana dashboard.
Need code to pull it out for flagging individual integrations.

**Comment by rh-codebase** [comment]
influx measurements  for power level monitoring. 1 minute cadence into 'snapmon3' and 4sec cadence into fenghires. Each have host and chan as tags.

snapmon3 contains:

**time, acc_len, chan, clip_count,  fft_shift, flag_threshold, host,   mjd, overflow_count, rms**

fenghires contains:

**time,  chan, host,   means,      mjd,               powers,     rmss,**

**Comment by caseyjlaw** [comment]
Moving this to #437
