### ISSUE TITLE
Cal-Im data management policy

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#240]
Cal-Im has more volatile (and faster) disks. We need to define how it can be used.

**Comment by yupinghuang** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by yupinghuang** [comment]
Here's a start https://github.com/ovro-lwa/calim-ops/wiki/0---Using-calim

**Comment by yupinghuang** [comment]
For the 24-hour run, who's gonna be using calim? @gregghallinan let's start from here

**Comment by caseyjlaw** [comment]
24-hr run plan managed in new commissioning sprint.
Yuping is data lead for 24-hr run. All cal-im nodes will have read access to others.
