### ISSUE TITLE
Errors when configuring x-engine 

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#247]
Nikita and I were going to try taking simultaneous beamformed + slow vis data. We were following the system use recipe; the settings we used for the system were whatever are defined in `./scripts/restoreSettings.sh `  and we used the config file in the `lwa_config_calim.yaml`. Pipelines started up okay. We ran into an issue when configuring the x-engine. We tried:
* Just configuring for slow vis
*  Just configuring for a beam with calibration
*  Just configuring for a beam _without_ calibration
*  Configuring for slow vis and a calibrated beam simultaneously
And consistently ran into issues. When configuring for slow vis, we get a sync_time key error:
![Screenshot from 2023-02-11 23-09-13](https://user-images.githubusercontent.com/29830471/218299178-561bf4ba-8df3-4236-9f4e-5cd868879e50.png)

when configuring for a beam, we get a chan0 key error:
![Screenshot from 2023-02-11 23-14-02](https://user-images.githubusercontent.com/29830471/218299210-24ddca89-d6b8-4055-8a3a-76a65568305f.png)

**Comment by yupinghuang** [comment]
https://github.com/ovro-lwa/lwa-issues/issues/162
https://github.com/ovro-lwa/lwa-issues/issues/210
potentially related.

I think it may be that the GPU nodes aren't getting any packets from the F engine. `like_bmon.py` on lxdlwagpu01 shows no traffic (and spot check a few other).

**Comment by yupinghuang** [comment]
![Screenshot from 2023-02-12 09-55-47](https://user-images.githubusercontent.com/15808145/218328262-c0c25410-bf47-41ed-9c6a-762910a6e6b0.png)
dashboard shows an cross corr accumulation length of 0 for SNAP1. It may be related.

**Comment by yupinghuang** [comment]
Yeah both of these errors are key errors from get_bifrost_status. A null check or something and then throwing a "hey the F engine is not talking to me" would be more helpful.

Reinitialized the F engines and configure_xengine went ok.

**Comment by caseyjlaw** [comment]
I added a try/except to catch these two errors and log a suggested solution.
