### ISSUE TITLE
rootless podman(aka podman) on calim

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#268]
Set up on calim09 but not other nodes

bunch ole admin work to do
https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md
https://www.redhat.com/sysadmin/nfs-rootless-podman

and then there's this fun apt thing https://github.com/containers/podman/issues/16193

the following suggested rebuilding images. There's another SO post which I can't find now that suggests putting root in a certain file having todo with sandbox user.
https://stackoverflow.com/questions/60042416/getting-permission-denied-even-as-root-inside-the-docker-container

**Comment by caseyjlaw** [comment]
These also has some tips for setting up subuid/subgid:
- https://docs.podman.io/en/latest/markdown/podman.1.html
- https://www.redhat.com/sysadmin/podman-rootless-overlay

This finally worked:

```
> echo $XDG_DATA_HOME
/data10/claw/
> podman --storage-opt ignore_chown_errors=true --storage-opt mount_program=/usr/bin/fuse-overlayfs pull lwaproject/lsl:pulsar
```

and maybe add this to /etc/subuid and /etc/subgid: `claw:10000:65536`  (maybe not actually required?).

No special configuration was required in .config/containers.

**Comment by caseyjlaw** [comment]
One more oddity... For some reason, setting XDG_DATA_HOME in my .bashrc does not let me see my rootless images. If I set it after log in, I can see them.

**Comment by yupinghuang** [comment]
Um. I think I orphaned my (rootful) containers. As in, they are still running but `sudo podman ps` isn't showing anything...

**Comment by yupinghuang** [comment]
ok in retrospect https://wiki.archlinux.org/title/XDG_Base_Directory setting `XDG_DATA_HOME` is probably a pretty bad idea.

**Comment by yupinghuang** [comment]
```
May 19 23:37:25 lwacalim10 sudo[1700670]:     claw : TTY=pts/6 ; PWD=/data10/claw ; USER=root ; COMMAND=/bin/rm /var/lib/containers/storage/libpod/bolt_state.db
```

um.....that explains it? This seems to be where podman stores its state info...

**Comment by yupinghuang** [comment]
ok note: the subuids and subgids should not overlap. Things broke on calim10 after the restart (low-freq-sky did not come up). They used to look like
```
(base) [pipeline@lwacalim10 ~]$ cat /etc/subuid
ubuntu:100000:65536
prometheus:165536:65536
claw:10000:65536
ea:10000:65536
nkosogor:100000:65536(base) [pipeline@lwacalim10 ~]$ cat /etc/subgid
ubuntu:100000:65536
prometheus:165536:65536
claw:10000:65536
ea:10000:65536
```
I modified them to look like
```
(base) [pipeline@lwacalim10 ~]$ cat /etc/subgid
ubuntu:100000:65536
prometheus:165536:65536
claw:200000:65536
ea:300000:65536
nkosogor:400000:65536
pipeline:400000:65536
(base) [pipeline@lwacalim10 ~]$ cat cat /etc/subuid
cat: cat: No such file or directory
ubuntu:100000:65536
prometheus:165536:65536
claw:200000:65536
ea:30000:65536
nkosogor:400000:65536
pipeline:400000:65536
```

**Comment by yupinghuang** [comment]
do as I say not as I do. I changed nkosogor's stuff to 500000 and up.

ok casey I think you needed all that arguments b/c of the overlapping gid/uids (probably).

so I guess todos are to give each user a user conf that points to a local storage and set up the sub gids and uids somehow on each node..? Good thing the subuids and be a reasonably big number https://wiki.gentoo.org/wiki/Subuid_subgid.

Also because of overlays after changing subuid/subgid/mount setting/graphroot and running `podman system migrate` it's typically necessary to remove everything in the previous graphroot because they might have bad permissions and stuff.

**Comment by nkosogor** [comment]
@caseyjlaw: Still get some errors:
ERRO[0000] Refreshing container e79f8b3114f89ea3ff87e28499c228159939fca7122d3520144145ad8c2836be: error acquiring lock 12 for container e79f8b3114f89ea3ff87e28499c228159939fca7122d3520144145ad8c2836be: file exists 
Error: OCI runtime error: runc: container_linux.go:380: starting container process caused: chdir to cwd ("/home/lwa/pulsar") set in config.json failed: operation not supported

**Comment by caseyjlaw** [comment]
Is that while trying to pull or run an image?
I tried to pull that on myself and ran into a quota limit. <sigh>

@yupinghuang did you confirm that you can pull and/or run an image after your changes?

**Comment by yupinghuang** [comment]
ok I'm still working on it. Permission hell re the error nikita is seeing. Somthing to do with the user uid in the container not having access to the graphroot.

@caseyjlaw you need a config file for containers that looks something like and then rm the containers graphroot in your home directory and then podman system migrate...

```
(base) [nkosogor@lwacalim10 ~]$ grep -v '#' .config/containers/storage.conf
[storage]
driver = "overlay"
runroot = "/run/user/1014"
graphroot = "/data10/nkosogor/containers"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,metacopy=on"
```

**Comment by caseyjlaw** [comment]
Ok, thanks. I cleaned things up as you suggested and can run migrate.
However, pulling an image reveals an issue. Perhaps this is what you are seeing too?
```
Error: writing blob: adding layer with blob "sha256:7ef69c36a18e85f5f49c516ec43b084851551b884568caaa01fea4fa8e28432a": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 72820:100 for /home/lwa/psrcat): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home/lwa/psrcat: invalid argument): exit status 1
```

**Comment by yupinghuang** [comment]
omg this is the worst thing ever.

I switched the OCI runtime to `crun` (basically `dnf install crun` and then modified `/etc/containers/containers.conf`) and then updated `fuse-overlayfs` to 1.11 (per updates on https://github.com/containers/podman/issues/16193 from 5 days ago since it fixes ACL stuff) and it works now. I can run

```
podman run -it -v /data10/nkosogor:/data lwaproject/lsl:pulsar
```

as nkosogor.

**Comment by yupinghuang** [comment]
> Ok, thanks. I cleaned things up as you suggested and can run migrate. However, pulling an image reveals an issue. Perhaps this is what you are seeing too?
> 
> ```
> Error: writing blob: adding layer with blob "sha256:7ef69c36a18e85f5f49c516ec43b084851551b884568caaa01fea4fa8e28432a": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 72820:100 for /home/lwa/psrcat): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home/lwa/psrcat: invalid argument): exit status 1
> ```

yeah for some reason it's requesting uids above 65536 so you need to give yourself a bigger number than that in the subgids and subuids.

Also -- slack me?

**Comment by yupinghuang** [comment]
ok. We are sticking with podman. Docs are up. https://github.com/ovro-lwa/calim-ops/wiki/Rootless-podman
