### ISSUE TITLE
lxdlwagpu03 lxd.daemon[7118]: => LXD failed to start

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#280]
and it keeps retrying and failing...doesn't look good?

**Comment by yupinghuang** [comment]
[loggy.log](https://github.com/ovro-lwa/lwa-issues/files/10885144/loggy.log)
looks like this thing is only on some nodes and not others (gpu01 doesn't seem to have it).

03, 05, 07 are the only nodes showing these log entries and they also seem to be the nodes which I am having trouble sending xengine commands to

**Comment by rh-codebase** [comment]
one can use:  sudo snap remove lxd
on hosts which do not require it.
lxd has been removed on lxdlwagpu03, 05,07

**Comment by yupinghuang** [comment]
Why were they there? The nodes didn't get reprovisioned after reboot,
correct?

**Comment by rh-codebase** [comment]
early on, gpu nodes were to be config. like dsa nodes but was then abandoned. Just left over cruft. The nodes do not get reprovisioned on reboot.
