### ISSUE TITLE
calim04 missing 40 GbE interface

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#282]
ref https://github.com/ovro-lwa/lwa-issues/issues/144 and all other prev issues related to this

``
(base) [ubuntu@lwacalim04 ~]$ lspci | grep -i ether
44:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
44:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
```

**Comment by rh-codebase** [comment]
ref #134  captures prev. steps taken.

**Comment by yupinghuang** [comment]
Actually -- gonna try restarting the node real quick

**Comment by yupinghuang** [comment]
It's back...Well that was easy
```
(base) [yuping@lwacalim04 ~]$ lspci | grep -i ether
44:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
44:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
c1:00.0 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)
c1:00.1 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)
```

pinging works
