### ISSUE TITLE
Data recorder: more helpful threads dying error msg?

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#288]
Maybe instead of checking for number of threads, check for the list of threads that ought to be running and report on the dead thread?

Sometimes getting "11 out of 10 threads active" or "8 out of 9 threads active" when it's etcd doing something weird can be alarming but not necessary to abort an obsie

**Comment by jaycedowell** [comment]
https://github.com/lwa-project/ovro_data_recorder/commit/7581eff17ddf943b29cd53650a32de2159f13821 works towards this but it needs testing.  Threads are now tracked by name and the error message will contain which of the monitored threads are missing.

**Comment by jaycedowell** [comment]
Seems to be working.
