### ISSUE TITLE
Make beam tracking not block

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#291]
I see two options

- run it in a different process
- Run it on the GPU nodes

Part of me feels like the latter makes more sense -- maybe have a command key track, either True or False, and then the GPU nodes can compute the delays and send to bifrost. The former is subject to etcd doing its thing and its latency and can potentially be inadequate when we want much more frequent updates

**Comment by caseyjlaw** [comment]
I believe @jaycedowell has a scheduler that would deal with this.

**Comment by jaycedowell** [comment]
I'm not sure if this is valid with the shift to session definition files.
