### ISSUE TITLE
create /data on cal-im

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#301]
Cal-Im nodes 1-8 each have a single /data0n directory. For analysis convenience, it would be nice for each cal-im node to have /data with cross-mounted data areas on 40 Gb network. Two options:
- /data/data0, /data/data1, ...
- /data0, /data1, ...

Opinions? Is using 40 Gb link going to interfere with real-time operations (data recorders)?

**Comment by yupinghuang** [comment]
Going over the 40 GbE is what we'd have to do anyway. It'd be nice to assign another 40GbE IP to the calim nodes and put those IP in a separate subnet (with the storage nodes).

The NFS mount should probably be read-only. Otherwise there maybe lots of chaos.

**Comment by yupinghuang** [comment]
All the data are mounted under `/mnt/24-hour-run`. The lowest two subbands are hosted on calim01. All other data are on calim00.
