### ISSUE TITLE
Beam observation of B1919+21

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#307]
Minimum of 2 beams:

1.  Beam on B1919+21
2.  Beam on Cygnus A
3.  Optional 3rd beam on zenith

**Comment by iveydavis** [comment]
The original goal of this observation was to look at a pulsar we can absolutely see because there was some issues pulling out the pulses for other pulsar observations. But Nikita and Jayce were able to resolve the problem and the pulses are popping out! The OVRO LWA power beams can indeed see pulsars.

![Image](https://user-images.githubusercontent.com/29830471/225970081-3781ab95-a8d4-41ac-9885-fc575935886f.png)



![Image](https://user-images.githubusercontent.com/29830471/225970118-e86b726e-b0c9-4069-a56a-84ebc18de34f.png)

**Comment by rh-codebase** [comment]
Is there an issue number describing what was wrong and how it was resolved? Is so, please cross-reference.

**Comment by iveydavis** [comment]
I don't think an issue was ever opened for the difficulty with pulsar detection. It ended up being an issue on the data processing side-- the pulsar signal was being flagged by the Presto software because it was so bright

**Comment by caseyjlaw** [comment]
@rh-codebase We are using github issues to track commissioning tasks. They are organized into the sprint topics as a "project". Sometimes the issue description is not a problem, but a feature, like this one.

**Comment by rh-codebase** [comment]
That's fine but without the explanation as to how this was resolved it left open whether it was a sw bug or something else.
