### ISSUE TITLE
SNAP01 ADC fails to calibrate

### ISSUE THREAD

**Issue by jack-h** [ovro-lwa/lwa-issues#315]
One of the ADC boards on SNAP01 fails to show any sign that it is clocking.

```
In [13]: f = snap2_fengine.Snap2Fengine('snap01')
2023-03-28 17:43:29,873 - lwa_f.blocks.block:snap01 - INFO - adc - Detected FMC ADC board on port 0
2023-03-28 17:43:30,109 - lwa_f.blocks.block:snap01 - INFO - adc - Detected FMC ADC board on port 1

In [14]: f.adc.adcs[1].read_clk_rates(0)
Out[14]: [7948, 795, 721, 0, 0] # BAD!

In [15]: f.adc.adcs[1].read_clk_rates(1)
Out[15]: [490608876, 98151914, 98125124, 98153030, 0] # Good looks like this
```

Reading the SPI reset register (via `f.adc.adcs[1].is_connected`) appears to suggest all the ADC chips are connected and powered up.

Possibly there is a fault with the clock feeding this board. Or, possibly something worse is at play.

**Comment by caseyjlaw** [comment]
See also #275

**Comment by jack-h** [comment]
Adding previously missing information --

 - FMC "B" is the innermost (furthest from the SNAP2 board edge) FMC port
 - The fact that the failure is on board `0` (`read_clk_rates(0)` is returning bad) indicates that the issue is on the "lower" ADC card in the FMC slot

**Comment by jack-h** [comment]
@Princemongo (is that Mark?!) has replaced ADC SN 21L with SN 5L, and all ADCs on SNAP01 now initialize correctly.

**Comment by caseyjlaw** [comment]
?! https://en.wikipedia.org/wiki/Prince_Mongo
