### ISSUE TITLE
Selection of antennas in fast visibility mode (48 antennas)

### ISSUE THREAD

**Issue by marinanderson** [ovro-lwa/lwa-issues#345]

**Comment by marinanderson** [comment]
See https://github.com/ovro-lwa/mnc_python/pull/20

**Comment by dgary50** [comment]
From Jack's Apr. 20 message at the link above, he reports that the data recording now works.  We would like to test this today if possible.

**Comment by dgary50** [comment]
@caseyjlaw @jack-h  I tried to take some fast visibility mode data after Marin reported things were working, but I could not get past the first command con.configure_xengine(recorders=['drvs'],full=True).  It prints the line 2023-06-06 20:52:10,660 - mnc.control - INFO - Stopping/starting pipelines, and then just hangs.  I had to ^Z and kill the job.  I tried again with the same result.  Perhaps some new outage occurred in the system in the short time after Marin's report?

**Comment by jack-h** [comment]
I think somebody might have alerted you to this, but we have now switched
in the deep ~512GB transient event buffers. Unfortunately this means it
takes a couple of minutes for the pipelines to do all their mallocing
before things work. I'm trying to find a workaround for this (it should be
possible to start the pipeline before the mallocing is complete)

**Comment by binchensun** [comment]
See the last antenna selection for fast visibility https://github.com/ovro-lwa/mnc_python/pull/32. Already merged to the main yml file.
