### ISSUE TITLE
Two data recorders not working

### ISSUE THREAD

**Issue by rlbyrne** [ovro-lwa/lwa-issues#352]
For slow visibility capture over the last few days, two data recorders haven't been working, resulting in two missing subbands of data. I am following the System Use Recipe and doing data capture as follows:
```
from mnc import control
con = control.Controller()
con.stop_xengine()
con.configure_xengine(recorders=['drvs'])
con.start_dr(recorders=['drvs'])
```
Running `con.status_dr()` returns this:
```
['0 recording; 14 idle; 2 timed out',
 'WARNING: drvs not fully operational: 2 sub-bands have not updated in 120 s: drvs8301,drvs8302',
 '0 recording; 14 idle; 2 timed out',
 'WARNING: drvf not fully operational: 2 sub-bands have not updated in 120 s: drvf8301,drvf8302',
 'idle',
 'idle',
 'idle',
 'idle']
```

**Comment by jaycedowell** [comment]
drvs8301 and drvs8302 are on lwacalim08.  The logs show that both those services were shut down on 4/12 and never restarted.

**Comment by rlbyrne** [comment]
@jaycedowell Thank you! How did you reboot them?

**Comment by jaycedowell** [comment]
I logged into lwacalim08 as pipeline and ran `~/ovro_data_recorder/services/start_dr_services.sh`.

**Comment by rh-codebase** [comment]
what calim machines  are the DR being run on?

**Comment by rlbyrne** [comment]
@rh-codebase calim00

**Comment by rh-codebase** [comment]
did the shutdown of DR on calim08 correspond to a reboot? If so, then they did not come back up on boot.
(base) [ubuntu@lwacalim08 ~]$ uptime
 00:44:03 up 4 days,  9:16,  1 user,  load average: 0.17, 0.67, 0.89

**Comment by rh-codebase** [comment]
@rlbyrne Jayce just said on calim08. Are you saying only on 08 and 00?

**Comment by rlbyrne** [comment]
@rh-codebase I was controlling the data recorder from calim00, but the issue was on calim08

**Comment by rh-codebase** [comment]
my question is which calim nodes run the start_dr_services.sh script?
