### ISSUE TITLE
The instructions for restarting the system are missing instructions for restarting the f-engine etcd services.

### ISSUE THREAD

**Issue by kathrynplant** [ovro-lwa/lwa-issues#356]
Could instructions for restarting the f-engine etcd services be added to this document, similar to the X-engine etcd services discussion in the power outage recovery section?  https://caltech.sharepoint.com/:w:/r/sites/ovro/projects/_layouts/15/Doc.aspx?sourcedoc=%7B7B5E0941-65DA-45AE-BF69-B6DD5961D2E5%7D&file=LWA-352_OoD_Procedures.docx&action=default&mobileredirect=true

Apologies if I'm looking at an out-of-date document, please point me to the one I should be using!

**Comment by caseyjlaw** [comment]
Thanks for the report. That is the correct doc. I've updated to include a reference to the service start script.
