### ISSUE TITLE
Trouble logging into lwacalimXX machines

### ISSUE THREAD

**Issue by akvydula** [ovro-lwa/lwa-issues#362]
I can log into calimh as a user, and into cailmXX as pipeline, but not with my user account.

on ubuntu@lwacalim00, my account seems not to exist:

```
[ubuntu@lwacalim00 ~]$ sudo su - akonakon
su: user akonakon does not exist
```

This may suggest a mismatch in user IDs b/w calimh and calimXX machines. 
@yupinghuang ?

**Comment by marinanderson** [comment]
I ran the last step in the Make New User instructions on the calim wiki here: https://github.com/ovro-lwa/calim-ops/wiki/9999-Admin#make-new-user

@akvydula , your user account should now exist on all the calim nodes! Give it a try, and reopen this issue if you're still unable to log on to any of the nodes.
