### ISSUE TITLE
Ant 255 issue

### ISSUE THREAD

**Issue by akvydula** [ovro-lwa/lwa-issues#411]
I am doing a single antenna beam former tests with Ant 255. The bowman plots on #rfimitigation plots show that both X and Y pol are seeing zero power as of 05/22/2023 through now (05/23/2023). However, I am seeing non-zero power levels on Y pol in the tests. These are 10s snapshots, beam=1, target=zenith and non-tracking. Tests are consistent in the last 24 hours or so. Plots on linear scale. (sorry about the bad labelling, all zeros are 'XX' and non-zeros are 'YY')
<img width="615" alt="image" src="https://github.com/ovro-lwa/lwa-issues/assets/45270277/7b6758a7-5474-46fe-b2ab-25cc9c048e67">

<img width="613" alt="image" src="https://github.com/ovro-lwa/lwa-issues/assets/45270277/74588f30-489a-42ec-bc70-123a1f0fbbe9">

**Comment by yupinghuang** [comment]
So it seems like all of the antennas without any autocorr plots are on SNAP 02. So it's more likely an issue with snap2 not responding to commands than an antenna refusing to be dead (there is ARX power on the report for ant 255).

The only anomalous entry I saw in the fengine etcd service log is 
```
/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/lwa_f/blocks/autocorr.py:208: RuntimeWarning: divide by zero encountered in true_divide
  spec = self._read_bram() / float(self.get_acc_len())
/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/lwa_f/blocks/autocorr.py:208: RuntimeWarning: invalid value encountered in true_divide
  spec = self._read_bram() / float(self.get_acc_len())
```
so..it looks like the accumulation length might have been set to 0 for the autocorr block for some reason?
