### ISSUE TITLE
calim node temperatures -- OK?

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#424]
Grafana is now plotting data from the calim nodes. Are the temperatures expected.

Dashboard: Linux Hosts, Job: CalimHosts

**Comment by yupinghuang** [comment]
I think for the most part they make sense? ones doing data recording are warmer than the ones not doing it. Although they're quite a bit warmer than I expected
![Screenshot from 2023-06-28 15-00-50](https://github.com/ovro-lwa/lwa-issues/assets/15808145/6d813310-0c8f-4a92-a36e-fb63100ef950)
![Screenshot from 2023-06-28 15-01-06](https://github.com/ovro-lwa/lwa-issues/assets/15808145/14b1e97c-b439-44e8-825b-a85c4256472b)

And...what's going on with the head node?? Does it have two different sets of temperature sensors..?
![Screenshot from 2023-06-28 15-01-32](https://github.com/ovro-lwa/lwa-issues/assets/15808145/d7c7b752-b8fb-4a97-b038-d58acfc962bc)

**Comment by rh-codebase** [comment]
Somewhere on the Grafana plot shows the critical temperature which is up around 90C IIRC. This value hopefully is coming back from the host so it seems that 60C, which does seem high, is well below critical.

head node:  does seem like a different sensor. Maybe the bios or some driver is mapping sensors differently into prometheus. That's a different matter so closing this out.
