### ISSUE TITLE
make mnc status display whether x engine and f engines are running/alive?

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#43]

**Comment by rh-codebase** [comment]
version info will also be provided.

**Comment by caseyjlaw** [comment]
Prototype of this is running on lxdlwagpu03 on port 5006.

**Comment by rh-codebase** [comment]
re-opening and labeling for webUI feature.

**Comment by caseyjlaw** [comment]
I'll suggest we close this and prioritize monitoring features in the system health dashboard. That's better supported by documents and procedures.
