### ISSUE TITLE
Non-blocking Beam Tracking

### ISSUE THREAD

**Issue by dgary50** [ovro-lwa/lwa-issues#439]
To prepare for daily operation of the solar beam (beam02), we need a way to track the beam from sunrise to sunset without the manual beam tracking now required, which also blocks the terminal from receiving further input.  This might be coordinated with other control procedures needed for daily solar observing (e.g. fast data recording).

**Comment by caseyjlaw** [comment]
This is certainly something we'd like to develop. There has been progress on scheduling via the generation of SDF files by Ivey at #321 and #326.

An interim solution to resolve the blocked terminal could use "screen" to keep a session open. I run this client that way to be ready to trigger the dr3 beam and voltage dumps based on alerts from LIGO and CHIME. https://github.com/ovrocaltech/ovro-alert/blob/main/ovro_alert/lwa_alert_client.py
