### ISSUE TITLE
lwa-cfg typo and change

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#44]
The lwa-antpos repo can parse a spreadsheet or pull values from etcd (pushed by lwa-cfg).
In testing, I found that the etcd has typo in field "latititude" (should be "latitude").
Also, the spreadsheet has a column "used", whereas etcd has one called "snap2_used". Are those the same? I actually thought "used" referred to the antenna, rather than the snap2, so the name used in etcd/cfg confuses me.

**Comment by rh-codebase** [comment]
The typo is fixed(now latitude) in code but service is lacking a 'reload' command. The current 'load' command requires a new version of the spreadsheet be committed to the lwa-cfg repo and this use case is for rebuilding the yml file and pushing fixes to etcd. Complete fix should be in today @ v1.3.0
