### ISSUE TITLE
x-engine logs grow too large

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#442]
The lxdlwagpu0x servers are running out of space in their home directory. I see four x-engine pipelines have filled four logs of several GB each that date back 8 months.
We should have a way to cap or roll those logs over.

**Comment by caseyjlaw** [comment]
I'll remove them and restart the x-engines for now (for my own purposes).

**Comment by jaycedowell** [comment]
The logs don't look like they have rolled on the couple of gpu servers I checked.  I would expected them to by now.  Could this be an environment problem?  The pipelines look to be running under casa.

**Comment by jaycedowell** [comment]
Nope, casa seems to have the correct version of `lwa352-pipeline.py`.  Strange.

**Comment by jaycedowell** [comment]
They seem to be rolling now.
