### ISSUE TITLE
Imaging pipeline Jul 27 + 2 weeks

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#449]
- [x] @yupinghuang to make scripts that generate bandpass cal and give solar folks path
- [x] @surajit4444mondal to get the solar casa pipeline (which takes one ms and spits out an image) to run under https://github.com/ovro-lwa/distributed-pipeline
- [x] solar script with infinite main loop goes in to orca/extra/solar @binchensun 
- [ ] @rlbyrne to poke @yupinghuang whenever the new cal scheme is ready for testing somewhat continuously
- [ ] and if we are feeling ambitious... @yupinghuang to make dirty IQUV images semi real-time

**Comment by yupinghuang** [comment]
@binchensun @surajit4444mondal See updated README at https://github.com/ovro-lwa/distributed-pipeline/blob/main/README.md

slack msg me if anything looks wrong!

**Comment by caseyjlaw** [comment]
Solar imaging script can run on one cal-im node with 10 min cadence and 10 min latency.

**Comment by yupinghuang** [comment]
I'm too ashamed to keep this issue going
