### ISSUE TITLE
Issues with casacore.tables functions in 'development' conda environment

### ISSUE THREAD

**Issue by nmahesh1412** [ovro-lwa/lwa-issues#451]
The simple getcol() function such as follows: 

>>> with tbl.table(data_path, readonly=True) as t:
       data = t.getcol('DATA',startrow)
... 
runs into the following error and exits python:

free(): invalid pointer
Aborted (core dumped)

**Comment by yupinghuang** [comment]
Does this happen in an ipython shell? I couldn't reproduce it

Also can you post how you started the jupyter session and also the cell where you do the import and what startrow is?

**Comment by caseyjlaw** [comment]
Closing, unless @nmahesh1412 still sees a problem.
