### ISSUE TITLE
Solar beam calibration or tracking fails

### ISSUE THREAD

**Issue by dgary50** [ovro-lwa/lwa-issues#463]
@caseyjlaw After you reset the system today (2023 Aug 22) I started the solar beamformer by loading the calibration files and starting the tracking.  However, the beamformed data have very low amplitude, which could be due to incorrect calibration or not tracking.  There was no obvious indication of an error during the process, so I am surprised to find the low amplitudes on reading the data.  I see some weak vestiges of solar events that look like the tracking was not correct (lots of structure in frequency), but that could also be caused by calibration issues.

When I tried to reload the calibration, configure_xengines() reported that the beam was already calibrated and gave a message "mnc.xengine_beamformer_control - INFO - Calibration already set for beam 2. To overload, use force=True".  However, configure_xengines() does not have that parameter and it seems not to be passed onward via *kwarg.

The 30-min spectrogram below resulted after I had stopped the tracking (first half of the period), then restarted it around the middle of the time period.

![image](https://github.com/ovro-lwa/lwa-issues/assets/16293957/26ea79a2-eded-4412-b225-23bfd31f7b6a)

**Comment by caseyjlaw** [comment]
Now that I think of it, I neglected to run the settings script to apply Larry's latest (both ARX and f-eng). The ARX were probably fine, but the f-eng gain would presumably be off after a reinitialization.
I'll add that as a feature to the f-eng restart function, as well as expose the force-calibration argument. As you noted, it is in an option for control at lower level, but not that function call.
