### ISSUE TITLE
LWA shelter temperature in etcd

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#47]
Do we have a LWA shelter temperature in etcd? I know we have some on the SNAP2s, but that is not considered representative.

**Comment by rh-codebase** [comment]
Discuss comments regarding a feature to auto shutdown linux hosts and possibly the ARX rack above some temperature threshold.

**Comment by rh-codebase** [comment]
LWA shelter temperature is now being measured via an Omega THX device which also measures dewpoint temperature and relative humidity. An omegaTHX service has been deployed to read this device and push into etcd under the /mon/lwashelter/ etcd key.
