### ISSUE TITLE
did we intend to deploy the latest ovro_data_recorder always?

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#485]
yesterday's telecon people reported quota management being weird.

I see that on calim the latest commit on the data recorder is the latest on https://github.com/lwa-project/ovro_data_recorder/commits/main, which means that it's possible that at some point in the last week, it was on commit https://github.com/lwa-project/ovro_data_recorder/commit/3b0a87ac4029fd7b1aad57732e1b72baf24e59bd, which would have broken quota management.

**Comment by yupinghuang** [comment]
Was 3b0a87a ever deployed on its own?

**Comment by jaycedowell** [comment]
Not that I am aware of.
