### ISSUE TITLE
fast vis still not working on lustre

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#489]
![image](https://github.com/ovro-lwa/lwa-issues/assets/15808145/fa9ef5e0-c1f1-4e27-a23c-3c4330804a28)

at about 800% gulp time.

**Comment by jaycedowell** [comment]
Is the plan for everything (slow, fast, power beams) to move to /lustre?

**Comment by yupinghuang** [comment]
Yes.

It might be worth removing the flush calls and see what happens. We know for sure that there's more than enough throughput to go around, but if there are synchronized read/write calls, the latency will be tricky.

**Comment by caseyjlaw** [comment]
@jaycedowell did your commit to the data recorder resolve this issue?
Also, how do you feel about having data recorders writing to lustre directly? Do you anticipate any issues?

**Comment by jaycedowell** [comment]
I don't know that writing to lustre has been tried again.  I haven't had a chance to try it.

**Comment by caseyjlaw** [comment]
@yupinghuang reported that there was an issue with python threading and the GIL not working well with high-latency writes to lustre. Could be a threading/multiprocessing change could get this to work.

**Comment by jaycedowell** [comment]
This also seems to be working after the latest round of updates.

**Comment by caseyjlaw** [comment]
Terrific!
