### ISSUE TITLE
Unclear if power beam recording is actually happening

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#500]
I've been intermittently running into issues where I'll start a beamformed observation, no errors are raised, the data recorder services report that they're recording, the terminal will report which file it is recording to (_i.e._, everything suggesting it's acting like a healthy beamformed observation), but the file doesn't exist. Even well after the recording is done, the file never comes to being. I've tried restarting the data recorders for the beams I'm using (dr5 and dr6) but it doesn't seem to help.

Related to this I suppose: where do the log files for the beamformers live now? They don't appear to be updated on /data0X/log anymore, I don't see anything in /lustre/pipeline, and I'm having trouble finding the relevant information on the new log GUI

**Comment by yupinghuang** [comment]
on kibana you can search for `@log_name: "dr-data01.pipeline.log.dr-beam-1.lwacalim01.log"` in the box up there. Or like just search "beam" and adjust the time range and go from there.

`/data0x/pipeline/log/` is where logs live
