### ISSUE TITLE
One mirrored vdev on GPU hosts is corrupted.

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#53]
Each GPU host was set up to have 2 mirrored vdevs backed by nvme. One of these mirrors on each host has become corrupted.

**Comment by rh-codebase** [comment]
BIOS renaming of disk devices may still be an issue. A number of GPU hosts would not boot due to the root fs being on the other ssd disk. root needs to be on the boot disk. Keeping open until more powercycles can be performed. As of now, all GPU hosts have their root fs on the Samsung boot disk as defined in MaaS and all zfs mirrors are online.

**Comment by jack-h** [comment]
Is this still a pending issue?

**Comment by rh-codebase** [comment]
closing.
