### ISSUE TITLE
Identify and prepare snapshot-all sky data

### ISSUE THREAD

**Issue by caseyjlaw** [ovro-lwa/lwa-issues#6]
15 MHz band and 2 hrs in a few windows. "quiet", "cas/cyg high", "cas/cyg low".

**Comment by caseyjlaw** [comment]
Data now ready at `/lustrepipeline/regression/exoplanet/`. Subbands 2-7.

**Comment by marinanderson** [comment]
Exoplanet / all-sky imaging data

3 2-hour datasets, spws 2–7
1. LST no peel
2. LST peel
3. LST with Cas/Cyg low on horizon (may be tricky for peeling)
