### ISSUE TITLE
3 new columns added to System Config Spreadsheet

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#83]
3 columns added on 2022.01.06 by Marin. e-mail:
"I have added 3 new columns to the System Configuration Spreadsheet, using the mapping information provided in Larry’s memo: Pol A/B FPGA Input # and Correlator Number."

**Comment by rh-codebase** [comment]
The 3 new columns have been added to the config parser and successfully parsed the new System Config Spreadsheet layout. Likely will be pushed into etcd after hearing back from others regarding other changes.

**Comment by caseyjlaw** [comment]
I know you want other feedback, but I'll just say I'm happy with the change and am ready to integrate it with my cable mapping visualization.

**Comment by rh-codebase** [comment]
service updated to v1.5.1 and excel spreadsheet pushed to etcd via webUI.
