### ISSUE TITLE
etcd command/response arx keys are not being deleted

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#92]
etcd key-space continues to increase. A dump of keys shows a large number of arx command/response keys. The command/response code does attempt to delete the key after obtaining the contents.

**Comment by rh-codebase** [comment]
have a potential fix. need test time. This may fix #262 type issues will have to see.

**Comment by yupinghuang** [comment]
any chance we can monitor/occasionally pull `put` latency/number of entries in the queue by key? Part of the feels like this might be present in other systems too.

**Comment by caseyjlaw** [comment]
This key issue may be related to a host of etcd performance issues (#262 #153 #290).
If we can address this (e.g., via a key TTL in subsystem control code), then we may be able to resolve them all.

**Comment by caseyjlaw** [comment]
I see a potential fix was mentioned in this thread. Did that get tested/evaluated? We're continuing to see erratic behavior in sync duration in etcd and that coincides with flaky control behavior.

**Comment by rh-codebase** [comment]
not yet. will need system time. likely next week

**Comment by yupinghuang** [comment]
Would throwing an NVMe at it be a possibly cheaper solution (mostly in terms of rick hours)

**Comment by rh-codebase** [comment]
fixed. v1.3.5 lwaARXserial and 2.6.0 etcdaccess (Golang repos). Verified response keys created for ARX no longer persist in etcd store. Removed all stale /resp/arx keys. (about 9k of them). Grafana etcd now showing about 3K keys. Most of these are /mon/corr and /mon/drvs types.
